---
#    - import_tasks: record_stats.yml
#      vars:
#        step: pre-runs

    - name: run test
      delegate_to: "{{vm_ip}}"
      include_role:
        name: run_sysbench_test

    - name: Polling sysbench test
      delegate_to: "{{vm_ip}}"
      include_role:
        name: polling_sysbench

#    - import_tasks: kill_stats.yml

    - name: Take a 5 second pause
      shell: sleep 5
      delegate_to: "{{vm_ip}}"

#    - import_tasks: clear_cache.yml

    - name: Clearing the Pagecache and Slabcache
      shell: "sync; echo 3 > /proc/sys/vm/drop_caches"

    - name: Restarting MySQL to clear the caches
      delegate_to: "{{vm_ip}}"
      run_once: true
      service:
        name: mysql
        state: restarted
...
